### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by loulou-99** [pnlbwh/pnlNipype#103]
Hi there,

Looking for some help with this installation. Please see output. Thank you!
[pnlNipype installation output.txt](https://github.com/pnlbwh/pnlNipype/files/10229140/pnlNipype.installation.output.txt)

**Comment by tashrifbillah** [comment]
pynrrd folks upgraded from Python 3.6. This is the error you ran into:

```
ERROR: Package 'pynrrd' requires a different Python: 3.6.15 not in '>=3.7'
                                                                              failed
CondaEnvException: Pip failed
```

Remove all `=` version string from https://github.com/pnlbwh/pnlpipe/blob/7f5128c0070a96b413fd3fa8686f67e953909f57/python_env/environment36.yml#L7 and try again.

**Comment by loulou-99** [comment]
I seemed to have the same issue after a few days of running. Wondering if I should remove = from other rows? 

This is my environment36.yml file: 

name: pnlpipe3

channels:
  - conda-forge

dependencies:
  - python
  - ipython
  - pytest
  - plumbum
  - future
  - numpy
  - pandas
  - vtk<=8.2.0
  - cmake
  - nibabel
  - nilearn
  - dipy<1.3.0
  - pyyaml
  - psutil
  - csvkit
  - gcc_linux-64<=7.3.0
  - gxx_linux-64<=7.3.0
  - joblib
  - matplotlib
  - conda-build
  - luigi
  - sqlalchemy
  - dash
  - statsmodels
  - tensorflow==1.12.0
  - keras==2.2.4
  - scikit-image
  - h5py<3
  - git
  - pip
  - pip:
     - git+https://github.com/SlicerDMRI/whitematteranalysis.git
     - git+https://github.com/dstrohl/Python_log_indenter.git
     - git+https://github.com/mhe/pynrrd.git
     - git+https://github.com/pnlbwh/conversion.git

**Comment by tashrifbillah** [comment]
Sure, remove them all and see if the environment builds for you.

**Comment by loulou-99** [comment]
Thanks - this fixed the issue. Could you advise how to fix this issue for installing the rest of the software? Thank you.

(pnlpipe3) jennifer@dart:~/pnlNipype> cmd/install.py UKFTractography
Cloning into 'ukftractography'...
fatal: unable to connect to github.com:
github.com[0: 140.82.112.4]: errno=Connection timed out

Traceback (most recent call last):
  File "/home/jennifer/pnlNipype/cmd/install.py", line 31, in <module>
    SoftwareCommand()
  File "/home/jennifer/miniconda3/envs/pnlpipe3/lib/python3.10/site-packages/plumbum/cli/application.py", line 177, in __new__
    return cls.run()
  File "/home/jennifer/miniconda3/envs/pnlpipe3/lib/python3.10/site-packages/plumbum/cli/application.py", line 634, in run
    retcode = inst.main(*tailargs)
  File "/home/jennifer/pnlNipype/cmd/install.py", line 28, in main
    softwareModule.make()
  File "/home/jennifer/pnlNipype/pnlpipe_software/UKFTractography.py", line 20, in make
    repo = downloadGithubRepo('pnlbwh/ukftractography', commit)
  File "/home/jennifer/pnlNipype/pnlpipe_software/__init__.py", line 102, in downloadGithubRepo
    git['clone', url] & FG
  File "/home/jennifer/miniconda3/envs/pnlpipe3/lib/python3.10/site-packages/plumbum/commands/modifiers.py", line 145, in __rand__
    cmd(
  File "/home/jennifer/miniconda3/envs/pnlpipe3/lib/python3.10/site-packages/plumbum/commands/base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
  File "/home/jennifer/miniconda3/envs/pnlpipe3/lib/python3.10/site-packages/plumbum/commands/base.py", line 252, in run
    return p.run()
  File "/home/jennifer/miniconda3/envs/pnlpipe3/lib/python3.10/site-packages/plumbum/commands/base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
  File "/home/jennifer/miniconda3/envs/pnlpipe3/lib/python3.10/site-packages/plumbum/commands/processes.py", line 304, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/home/jennifer/miniconda3/envs/pnlpipe3/lib/python3.10/site-packages/plumbum/commands/processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/home/jennifer/miniconda3/envs/pnlpipe3/lib/python3.10/site-packages/plumbum/machines/base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 128
Command line: | /home/jennifer/miniconda3/envs/pnlpipe3/bin/git clone git://github.com/pnlbwh/ukftractography.git

**Comment by tashrifbillah** [comment]
> /home/jennifer/miniconda3/envs/pnlpipe3/bin/git clone git://github.com/pnlbwh/ukftractography.git

Does this raise the same error directly on your terminal?

**Comment by loulou-99** [comment]
Yes.

Output: 

(pnlpipe3) jennifer@dart:~> /home/jennifer/miniconda3/envs/pnlpipe3/bin/git clone git://github.com/pnlbwh/ukftractography.git
Cloning into 'ukftractography'...
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=Connection timed out

**Comment by tashrifbillah** [comment]
The problem is that your shell is using `git` protocol as opposed to intended `https` protocol to clone GitHub and I do not understand why it is doing so. It did not happen for other users.

**Comment by loulou-99** [comment]
Thanks, I will see if our developers can assist in a work around.

**Comment by tashrifbillah** [comment]
Hi, I have been able to reproduce your issue at our end. It appears that something has changed with GitHub. Will follow up with a fix.

**Comment by tashrifbillah** [comment]
Jennifer:

I want you to do two things:

```bash
cd ~/pnlNipype/
git pull origin master
git submodule update
```

Now my fix will be available in your computer. Then you can resume installation:

```bash
cd ~/pnlNipype/
cmd/install.py UKFTractography
```

**Comment by loulou-99** [comment]
Thanks. 

I was successful with dcm2niix and tract_querier, but did throw errors with UKFTractography and ANTs (outputs attached).

[UKF - dec30.txt](https://github.com/pnlbwh/pnlNipype/files/10326722/UKF.-.dec30.txt)
[ANTs - dec30.txt](https://github.com/pnlbwh/pnlNipype/files/10326723/ANTs.-.dec30.txt)

**Comment by tashrifbillah** [comment]
Jennifer, consider using our pre-built [docker or singularity](https://github.com/pnlbwh/pnlpipe-containers) containers. The errors you are running into are user-specific and require good programming knowledge on part of the user to solve.

**Comment by loulou-99** [comment]
Hi there, I was able to reproduce these errors on a separate machine/OS. Please confirm that this error is user-specific.
