### ISSUE TITLE
nifti_fs not working

### ISSUE THREAD

**Issue by sbouix** [pnlbwh/pnlNipype#11]
(pnlpipe3) -bash-4.2$ nifti_fs -i testt1.nii.gz -m testmask3-mask.nii.gz -n 20 -o /tmp/fs
2019-07-25 05:07:17,039 /mnt/localhome/testpnlpipe/software/pnlNipype/exec/nifti_fs INFO  Mask the t1
Traceback (most recent call last):
  File "/mnt/localhome/testpnlpipe/software/pnlNipype/exec/nifti_fs", line 128, in <module>
    App.run()
  File "/mnt/localhome/testpnlpipe/software/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/plumbum/cli/application.py", line 572, in run
    retcode = inst.main(*tailargs)
  File "/mnt/localhome/testpnlpipe/software/pnlNipype/exec/nifti_fs", line 75, in main
    t1 = tmpdir / 't1masked.nii.gz'
TypeError: unsupported operand type(s) for /: 'str' and 'str'

**Comment by tashrifbillah** [comment]
For `fs.py`: it has been a quick fix. We also need to define `tmpdir` as a local path object so assignment like `tmpdir / 't1masked.nii.gz'` are valid:
> tmpdir = local.path(tmpdir)

This additional definition was not in `pnlpipe`. I shall take a closer look at it.
Rest assured, `nifti_fs` is up and running now.

I shall check in my change soon.

**Comment by tashrifbillah** [comment]
Fixed by https://github.com/pnlbwh/pnlNipype/commit/4422e9a1673adce9899604812a05664beb66cbc3

Issue marked for closing
