### ISSUE TITLE
Eddy_openmp

### ISSUE THREAD

**Issue by kavandeloo** [pnlbwh/pnlNipype#110]
Hi there, 

I get an error when trying to run fsl_topup_epi_eddy. I am using Python 3.10, and have FSL v6.0.4. I see that eddy_openmp is not located in fsl/usr/bin; it seems that it is no longer present in newer versions of FSL. Is there a work around? We are using a Macbook. The error is below as well. 

Thanks!

--------------------------------------

(pnlpipe3) phillipslab@Phillipss-MacBook-Pro test % fsl_topup_epi_eddy --imain sub-TRD027_ses-01_desc-Xc_dwi.nii.gz,sub-TRD027_ses-01_desc-Xc_dwi_PA.nii.gz --bvals sub-TRD027_ses-01_desc-Xc_dwi.bval --bvecs sub-TRD027_ses-01_desc-Xc_dwi.bvec --numb0 -1 --whichVol 1,2 --acqp acqp.txt --config eddy_config.txt --out ./fsltopupeddy

Traceback (most recent call last):

  File "/Users/phillipslab/pnlNipype/exec/fsl_topup_epi_eddy", line 572, in <module>

    TopupEddyEpi.run()

  File "/Users/phillipslab/fsl/lib/python3.10/site-packages/plumbum/cli/application.py", line 633, in run

    retcode = inst.main(*tailargs)

  File "/Users/phillipslab/pnlNipype/exec/fsl_topup_epi_eddy", line 131, in main

    from plumbum.cmd import eddy_openmp

ImportError: cannot import name 'eddy_openmp' from 'plumbum.cmd' (/Users/phillipslab/fsl/lib/python3.10/site-packages/plumbum/cmd.py)

(pnlpipe3) phillipslab@Phillipss-MacBook-Pro test % export PATH=//Users/phillipslab/fsl/bin/eddy_openmp:$PATH

(pnlpipe3) phillipslab@Phillipss-MacBook-Pro test % fsl_topup_epi_eddy --imain sub-TRD027_ses-01_desc-Xc_dwi.nii.gz,sub-TRD027_ses-01_desc-Xc_dwi_PA.nii.gz --bvals sub-TRD027_ses-01_desc-Xc_dwi.bval --bvecs sub-TRD027_ses-01_desc-Xc_dwi.bvec --numb0 -1 --whichVol 1,2 --acqp acqp.txt --config eddy_config.txt --out ./fsltopupeddy

Traceback (most recent call last):

  File "/Users/phillipslab/pnlNipype/exec/fsl_topup_epi_eddy", line 572, in <module>

    TopupEddyEpi.run()

  File "/Users/phillipslab/fsl/lib/python3.10/site-packages/plumbum/cli/application.py", line 633, in run

    retcode = inst.main(*tailargs)

  File "/Users/phillipslab/pnlNipype/exec/fsl_topup_epi_eddy", line 131, in main

    from plumbum.cmd import eddy_openmp

ImportError: cannot import name 'eddy_openmp' from 'plumbum.cmd' (/Users/phillipslab/fsl/lib/python3.10/site-packages/plumbum/cmd.py)

**Comment by tashrifbillah** [comment]
> I see that eddy_openmp is not located in fsl/usr/bin; it seems that it is no longer present in newer versions of FSL

Katie, this cannot be right. Locate the actual *binary* directory and do `ls eddy_*`. You will see all eddy commands there. Our binary directory is `where_you_installed_fsl/bin/` on 6.0.6--which is more advanced than yours. There is no `usr/` in between.

**Comment by kavandeloo97** [comment]
Hi Tashrif, I think that eddy_openmp is replaced by eddy_cpu in FSL 6.0.6 or later.

https://github.com/Washington-University/HCPpipelines/issues/264

**Comment by tashrifbillah** [comment]
Thanks for letting us know, Katie.
